ThesisWebExpeDjango/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('expe.urls', namespace='expe')),
    path('admin/', admin.site.urls),
]

expe/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'expe'

urlpatterns = [
    path('', views.expe_list, name='expe_list'),
    path('expe', views.expe, name='expe'),
    path('indications', views.indications, name='indications'),
    path('admin/results', views.list_results, name='results'),
    path('admin/results/<str:expe>', views.list_results, name='results_expe'),
    path('admin/download', views.download_result, name='download')
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expe/models.py
from django.db import models

# Create your models here.

expe/views.py
# django imports
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import Http404

# main imports
import os
import json
import base64
import random
import numpy as np
from datetime import datetime
import pickle 
import time
import zipfile
from io import BytesIO


# expe imports
from .expes.classes.quest_plus import QuestPlus
from .expes.classes.quest_plus import psychometric_fun

from .expes import run as run_expe

# image processing imports
import io
from PIL import Image, ImageDraw

# module imports
from .utils import api
from .utils import functions

from .utils.processing import crop_images
from . import config as cfg


def get_base_data(expe_name=None):
    '''
    Used to store default data to send for each view
    '''
    data = {}

    data['BASE'] = settings.WEBEXPE_PREFIX_URL

    # if expe name is used
    if expe_name is not None:
        data['javascript'] = cfg.expes_configuration[expe_name]['javascript']

    return data


def expe_list(request):

    # get all scenes from dataset
    scenes = api.get_scenes()

    # get list of experimentss
    expes = cfg.expe_name_list
    data = get_base_data()

    # by default user restart expe
    request.session['expe_started'] = False

    # get base data
    data = get_base_data()
    # expe data
    data['scenes'] = scenes
    data['expes']  = expes
    
    #data['scenes'] = {}
    #for expe in expes:
    #    if 'scene' in cfg.expes_configuration[expe]:
    #        data['scenes'][expe] = cfg.expes_configuration[expe]['scenes']
    #    else:
    #        data['scenes'][expe] = scenes
            
    return render(request, 'expe/expe_list.html', data)


def indications(request):

    #random.seed(10)

    # get param 
    expe_name = request.GET.get('expe')
    

    
    scene_name = None
    if 'scene' in request.GET:
        scene_name = request.GET.get('scene')
    
    if scene_name is None or scene_name == 'null':
        scene_name = random.choice(cfg.expes_configuration[expe_name]['scenes'])
        
    example_number = request.GET.get('example')

    print(example_number)

    # get base data
    data = get_base_data()
    # expe parameters
    data['expe_name']  = expe_name
    data['scene_name'] = scene_name
    data['question']   = cfg.expes_configuration[expe_name]['text']['question']
    data['indication'] = cfg.expes_configuration[expe_name]['text']['indication']

    number_of_examples = len(cfg.expes_configuration[expe_name]['text']['examples']['images'])

    start_experiment = False
    if (int(example_number) >= number_of_examples):
        start_experiment = True
    else:
         # run expe method using `expe_name`
        function_name = 'example_' + expe_name
    
        try:
            run_example_method = getattr(run_expe, function_name)
        except AttributeError:
            raise NotImplementedError("Run expe method `{}` not implement `{}`".format(run_expe.__name__, function_name))
    
        data_example = run_example_method(request, expe_name, scene_name)
        data.update(data_example)
         
        # get expected image qualities indices (load noisy and ref image)
#        params_image = cfg.expes_configuration[expe_name]['text']['examples']['images'][int(example_number)]
#        qualities = api.get_scene_qualities(scene_name)
#
#        noisy_quality = qualities[params_image[0]]
#        ref_quality = qualities[params_image[1]]
#
#        noisy_image = api.get_image(scene_name, noisy_quality)
#        ref_image = api.get_image(scene_name, ref_quality)
#
#        # get crop params from configuration
#        crop_params = cfg.expes_configuration[expe_name]['text']['examples']['crop_params'][int(example_number)]
#
#        img_merge, percentage, orientation, position = crop_images(noisy_image,     
#                                                                    ref_image, 
#                                                                    per=crop_params[0], 
#                                                                    orien=crop_params[1], 
#                                                                    swap_img=crop_params[2])
#        width, height = img_merge.size
#        if orientation==0:
#            left, top, right, bottom = percentage*width, 0, percentage*width, height   #vertical
#        else:
#            left, top, right, bottom = 0, percentage*height, width, percentage*height   #horizontal
#        if  int(example_number) % 2 != 0 :
#            if noisy_quality != qualities[-1]:#-noisy_quality > qualities[-1]-(10*qualities[-1])/100 :
#                draw = ImageDraw.Draw(img_merge) 
#                draw.line((left, top, right, bottom), fill='black', width=5)
#        example_sentence = cfg.expes_configuration[expe_name]['text']['examples']['sentence'][int(example_number)]
#
#        if orientation == 0:
#            example_sentence = example_sentence.format('vertically', str(percentage*100))
#        else:
#            example_sentence = example_sentence.format('horizontally', str(percentage*100))
#
#        data['example_sentence'] = example_sentence
#
#
#        # Temporary save of image
#        tmp_folder = os.path.join(settings.MEDIA_ROOT, cfg.output_tmp_folder)
#
#        if not os.path.exists(tmp_folder):
#            os.makedirs(tmp_folder)
#
#        # generate tmp merged image (pass as BytesIO was complicated..)
#        filepath_img = os.path.join(tmp_folder, 'example_' + scene_name + '' + expe_name + '.png')
#        
#        # replace img_merge if necessary (new iteration of expe)
#        if img_merge is not None:
#            img_merge.save(filepath_img)
#
#        print(filepath_img)
#        data['example'] = filepath_img

    data['start'] = start_experiment

    return render(request, 'expe/expe_indications.html', data)


# Create your views here.
def expe(request):
    
    # get param 
    expe_name = request.GET.get('expe')
    scene_name = request.GET.get('scene')
    
    # unique user ID during session (user can launch multiple exeperiences)
    if 'id' not in request.session:
        request.session['id'] = functions.uniqueID()

    # first time expe is launched add expe information
    if 'expe' not in request.session or expe_name != request.session.get('expe'):
        refresh_data(request, expe_name, scene_name)

    # refresh if scene_name changed
    if 'scene' not in request.session or scene_name != request.session.get('scene'):
        refresh_data(request, expe_name, scene_name)

    # create output folder for expe_result
    current_day = datetime.strftime(datetime.utcnow(), "%Y-%m-%d")

    user_identifier = request.session.get('id')
    experiment_id = request.session.get('experimentId')

    print("ExperimentId is : " + experiment_id)

    # check if experimentId is used or not
    if len(experiment_id) == 0:
        output_expe_folder = cfg.output_expe_folder_name_day.format(expe_name, current_day, user_identifier)
    else:
        output_expe_folder = cfg.output_expe_folder_name_id_day.format(expe_name, experiment_id, current_day, user_identifier)

    results_folder = os.path.join(settings.MEDIA_ROOT, output_expe_folder)
    if not os.path.exists(results_folder):
        os.makedirs(results_folder)

    result_filename = scene_name + '_' + request.session.get('timestamp') +".csv"
    results_filepath = os.path.join(results_folder, result_filename)

    if not os.path.exists(results_filepath):
        output_file = open(results_filepath, 'w')
        functions.write_header_expe(output_file, expe_name)
    else:
        output_file = open(results_filepath, 'a')

    # TODO : add crontab task to erase generated img and model data
    # create `quest` object if not exists    
    models_folder = os.path.join(settings.MEDIA_ROOT, cfg.model_expe_folder.format(expe_name, current_day))

    if not os.path.exists(models_folder):
        os.makedirs(models_folder)

    model_filename = result_filename.replace('.csv', '.obj')
    model_filepath = os.path.join(models_folder, model_filename)

    # run expe method using `expe_name`
    function_name = 'run_' + expe_name

    try:
        run_expe_method = getattr(run_expe, function_name)
    except AttributeError:
        raise NotImplementedError("Run expe method `{}` not implement `{}`".format(run_expe.__name__, function_name))

    expe_data = run_expe_method(request, model_filepath, output_file)

    if request.session.get('expe_finished'):
        # reinit session as default value
        # here generic expe params
        del request.session['expe']
        del request.session['scene']
        del request.session['experimentId']
        del request.session['qualities']
        del request.session['timestamp']

        # specific current expe session params (see `config.py`)
        for key in cfg.expes_configuration[expe_name]['session_params']:
            del request.session[key]

    # set expe current data into session (replace only if experiments data changed)
    if expe_data is not None:
        request.session['expe_data'] = expe_data

        # get base data
    data = get_base_data(expe_name)

    # other experimentss information
    data['expe_name']            = expe_name
    data['end_text']             = cfg.expes_configuration[expe_name]['text']['end_text']

    return render(request, cfg.expes_configuration[expe_name]['template'], data)


@login_required(login_url="login/")
def list_results(request, expe=None):
    """
    Return all results obtained from experimentss
    """

    if expe is None:
        folders = cfg.expe_name_list

        return render(request, 'expe/expe_results.html', {'expe': expe, 'folders': folders})

    else:
        if expe in cfg.expe_name_list:

            folder_date_path = os.path.join(settings.MEDIA_ROOT, cfg.output_expe_folder_date, expe)

expe/templates/expe/expe.html
{% extends 'base.html' %}

{% load static %}
{% load apptags %}

{% block title %}
    Expe {{ expe_name }}
{% endblock %}

{% block content %}
    
    {% if request.session.expe_finished %}
        <h3>{{end_text}}</h3>

        <br />
        <p>You will be redirected in <span id="refreshTime">5</span> sec to home page</p>
    {% endif %}

    <!-- TODO : Load    img from bitmap with javascript `loadImg.js` -->
    {% if not request.session.expe_finished %}
        <img id="expeImg" src="{{request.session.expe_data|get_value_from_dict:'image_path'}}" data-img="{{request.session.img_merged}}"/>
    {% endif %}

    {% block javascripts %}
 
    {% endblock %}
{% endblock %}

expe/templates/expe/expe_indications.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Expe {{ expe_name }}
{% endblock %}

{% block content %}
    
    <h3>{{question}}</h3>
    <br />
    <h5>{{indication}}</h5>

    {% if start %}
        <br />
        <br />

        <div class="row">
            <div class="col-md-4 offset-md-4">
                <form method="GET" action="/expe">
                    <div class="form-group">
                        <input type="hidden" name="scene" value="{{scene_name}}"/>
                        <input type="hidden" name="expe" value="{{expe_name}}"/>
                        <input type="hidden" name="iteration" value="0"/>

                        <label for="experimentId">Select experiment identifier:</label>
                        <input type="text" class="form-control" name="experimentId" placeholder="Enter your experiment identifier"/>
                    </div>
                </form>
            </div>
        </div>

        <p id="expeIndication"><strong>Press enter to begin experiments</strong></p>
    {% else %}
        <input type="hidden" name="scene_name" value="{{scene_name}}"/>
        <br/>
        <h5>{{example_sentence|linebreaks}}</h5>
        <img src="{{example}}" />
    {% endif %}

{% endblock %}

{% block javascripts %}
    <script src="{% static "js/indications.js" %}"></script>
{% endblock %}

expe/templates/expe/expe_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Expe choice
{% endblock %}

{% block content %}
    <h2>Choose your experiments and dataset</h2>

    <div class="row">
        <div class="col-md-4 offset-md-4">

            <form action="/indications" id="expeChoice">

                <input type="hidden" name="example" value="0"/>

                <div class="form-group">
                    <label for="expe" style="position:static">Select experiments:</label>
                    <select class="form-control " name="expe">
                        {% for expe in expes %}
                            <option value="{{expe}}">{{expe}}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <!-- <div class="form-group">
                    <label for="scene">Select scene:</label>
                    <select class="form-control" name="scene">
                        {% for scene in scenes. %}
                            <option value="{{scene}}">{{scene}}</option>
                        {% endfor %}
                    </select>
                </div> -->


                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    {% block javascripts %}

    {% endblock %}
{% endblock %}

expe/templates/expe/expe_results.html
{% extends 'base.html' %}

{% load static %}
{% load apptags %}

{% block title %}
    Expe {{ expe_name }}
{% endblock %}

{% block content %}
    
    {% if not expe %}
        <h3>Results files of experiments</h3>
        <br />
    {% endif %}

    <div class="results-expe">

        {% if expe %}
            <div class="alert alert-info" role="alert">
                <h4 class="alert-heading"><strong>Experience:</strong> {{expe}}</h4>
                <hr>
                <p><strong>Question:</strong> {{infos.question}} </p>
                <p class="mb-0"><strong>Indication:</strong> {{infos.indication}} </p>
            </div>

            <br/>
            {% if folders %}

                <!-- List of items which has identifier when user pass experiment -->
                <h3>By experiment identifier</h3>
                <ul class="list-group">
                    {% with folders|get_value_from_dict:'expeId' as id_folder %}

                        {% for id_name, id in id_folder.items %} 
                                            
                            <li class="list-group-item">
                                
                                <div class="row">
                                    <div class="col-md-10">{{id_name}} </div>
                                    <div class="col-md-1 download-list" data-download-path="expeId/{{expe}}/{{id_name}}"><i class="fas fa-download"></i></div>
                                    <div class="col-md-1 date-folder-list"><i class="fas fa-arrow-circle-right"></i></div>
                                </div>
                                
                                <ul class="list-group files-list" style="display: none">

                                    <hr />
                                    
                                    {% for day_name, day in id.items %} 
                                        
                                        <li class="list-group-item">
                                            
                                            <div class="row">
                                                <div class="col-md-10">{{day_name}} </div>
                                                <div class="col-md-1 download-list" data-download-path="expeId/{{expe}}/{{id_name}}/{{day_name}}"><i class="fas fa-download"></i></div>
                                                <div class="col-md-1 date-folder-list"><i class="fas fa-arrow-circle-right"></i></div>
                                            </div>
                                            
                                            <ul class="list-group files-list" style="display: none">

                                                <hr />
                                                
                                                {% for user_name, user in day.items %}

                                                <li class="list-group-item">

                                                        <div class="row">
                                                            <div class="col-md-10"><strong>User: </strong>{{user_name}} </div>
                                                            <div class="col-md-1 download-list" data-download-path="expeId/{{expe}}/{{id_name}}/{{day_name}}/{{user_name}}"><i class="fas fa-download"></i></div>
                                                            <div class="col-md-1 date-folder-list"><i class="fas fa-arrow-circle-right"></i></div>
                                                        </div>
                                                        

                                                        <ul class="list-group files-list" style="display: none">

                                                            <hr />
                                                            {% for file in user %}

                                                                <li class="list-group-item">
                                                                
                                                                    <div class="row">
                                                                        <div class="col-md-11">{{file}}</div>
                                                                        <div class="col-md-1 download-list" data-download-path="expeId/{{expe}}/{{id_name}}/{{day_name}}/{{user_name}}/{{file}}"><i class="fas fa-download"></i></div>
                                                                    </div>
                                                                            
                                                                </li>
                                                            {% endfor %}
                                                        
                                                        </ul>
                                                </li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                    {% endfor %} 

                                    </ul>
                                </li>
                            {% endfor %} 
                    {% endwith %}
                </ul>


                <!-- List of items which does not have identifier when user pass experiment -->
                <h3>By date</h3>
                <ul class="list-group">
                
                    {% with folders|get_value_from_dict:'date' as date_folder %}
                        {% for day_name, day in date_folder.items %} 
                            
                                <li class="list-group-item">
                                    
                                    <div class="row">
                                        <div class="col-md-10">{{day_name}} </div>
                                        <div class="col-md-1 download-list" data-download-path="date/{{expe}}/{{day_name}}"><i class="fas fa-download"></i></div>
                                        <div class="col-md-1 date-folder-list"><i class="fas fa-arrow-circle-right"></i></div>
                                    </div>
                                    
                                    <ul class="list-group files-list" style="display: none">

                                        <hr />
                                        
                                        {% for user_name, user in day.items %}

                                        <li class="list-group-item">

                                                <div class="row">
                                                    <div class="col-md-10"><strong>User: </strong>{{user_name}} </div>
                                                    <div class="col-md-1 download-list" data-download-path="date/{{expe}}/{{day_name}}/{{user_name}}"><i class="fas fa-download"></i></div>
                                                    <div class="col-md-1 date-folder-list"><i class="fas fa-arrow-circle-right"></i></div>
                                                </div>
                                                

                                                <ul class="list-group files-list" style="display: none">

                                                    <hr />
                                                    {% for file in user %}

                                                        <li class="list-group-item">
                                                        
                                                            <div class="row">
                                                                <div class="col-md-11">{{file}}</div>
                                                                <div class="col-md-1 download-list" data-download-path="date/{{expe}}/{{day_name}}/{{user_name}}/{{file}}"><i class="fas fa-download"></i></div>
                                                            </div>
                                                                    
                                                        </li>
                                                    {% endfor %}
                                                
                                                </ul>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </li>
                        {% endfor %} 
                    {% endwith %}


                </ul>

            {% csrf_token %}

            {% else %}
                <div class="alert alert-warning" role="alert">
                    <i>Expe folder is empty</i>
                </div>
            {% endif %}
        {% else %}
             {% for f in folders %}
                <ul class="list-group">
                    <a href="{% url 'expe:results_expe' expe=f %}">
                        <li class="list-group-item">{{f}}</li>
                    </a>
                </ul>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript"> 
        // Utils informations
        var expe_name = "{{expe}}"
    </script>
    <script src="{% static "js/results.js" %}"></script>
    <script src="{% static "js/FileSaver.js" %}"></script>
{% endblock %}